import glob
import os
import tempfile
import unittest

from cookiecutter.main import cookiecutter
from slugify import slugify

"""
This test is for verifying that cookiecutters work without failing, and for debugging them if they fail. This test 
doesn't make any assertions about the output generated by cookiecutters.

This test file globs for any cookiecutter.json files, and will create a separate test function for every cookiecutter
it detected.
"""


class TestsContainer(unittest.TestCase):
    longMessage = True


def make_test_function(cookiecutter_dir):
    def test(self):
        cookiecutter(cookiecutter_dir, output_dir=tempfile.mkdtemp(), no_input=True)

    return test


if __name__ == '__main__':
    cookiecutters = glob.glob('./**/cookiecutter.json', recursive=True)
    for path in cookiecutters:
        cookiecutter_basedir = os.path.dirname(path)
        test_name = slugify(cookiecutter_basedir, separator='_')
        test_func = make_test_function(cookiecutter_basedir)
        setattr(TestsContainer, 'test_{0}'.format(test_name), test_func)

    unittest.main(verbosity=2)
